# 拽抓  专 转  砖专转 砖爪 砖专

- "   转":
    - Jellyfin:
        icon: jellyfin.svg
        href: https://jellyfin.mbs-home.ddns.net
        description: "砖专转  转拽 - 住专 砖 住专, 住专转 拽 注 砖拽 驻 "
        server: my-docker
        container: jellyfin

    - Sonarr:
        icon: sonarr.svg
        href: https://sonarr.mbs-home.ddns.net
        description: "  砖 住专转 - 专, 专 注  砖 住专转 TV"
        server: my-docker
        container: sonarr

    - Radarr:
        icon: radarr.svg
        href: https://radarr.mbs-home.ddns.net
        description: "  砖 住专 - 专, 专 注  砖 住专"
        server: my-docker
        container: radarr

    - Lidarr:
        icon: lidarr.svg
        href: https://lidarr.mbs-home.ddns.net
        description: "  砖 拽 - 专, 专 注  砖 拽"
        server: my-docker
        container: lidarr

    - Bazarr:
        icon: bazarr.svg
        href: https://bazarr.mbs-home.ddns.net
        description: " 转转  - 专 注  砖 转转 住专 住专转"
        server: my-docker
        container: bazarr

- "猬锔 专转 砖转祝":
    - Transmission:
        icon: transmission.svg
        href: https://transmission.mbs-home.ddns.net
        description: "拽 专 转拽 - 专 专  砖 拽爪 专 BitTorrent"
        server: my-docker
        container: transmission

    - Prowlarr:
        icon: prowlarr.svg
        href: https://prowlarr.mbs-home.ddns.net
        description: " 拽住专 - 驻砖  砖 转专 专 拽住专"
        server: my-docker
        container: prowlarr

    - slskd:
        icon: slskd.svg
        href: https://slskd.mbs-home.ddns.net
        description: "砖转祝 拽 Soulseek - 砖转祝 专转 拽 专 专砖转 Soulseek"
        server: my-docker
        container: slskd

- "  注专转":
    - Portainer:
        icon: portainer.svg
        href: https://portainer.mbs-home.ddns.net
        description: " Docker - 砖拽 专驻 转拽  拽专, 转转 专砖转转"
        server: my-docker
        container: portainer

    - Traefik:
        icon: traefik.svg
        href: https://traefik.mbs-home.ddns.net
        description: "Reverse Proxy -  转注专转 专砖转, SSL  注住  砖专转"
        server: my-docker
        container: traefik

    - AdGuard Home:
        icon: adguard-home.svg
        href: https://dns.mbs-home.ddns.net
        description: "住 驻专住转 -DNS - 住转 驻专住转, 注拽 驻专 DNS 专转 专砖转"
        server: my-docker
        container: adguard

- " 专 ":
    - Grafana:
        icon: grafana.svg
        href: https://monitor.mbs-home.ddns.net
        description: "砖专 专 转拽 - 爪 砖 , 专驻 爪 砖 注专转"
        server: my-docker
        container: grafana

    - Prometheus:
        icon: prometheus.svg
        href: https://prometheus.mbs-home.ddns.net
        description: "住祝  - 住祝 住  爪注 砖  砖专转 注专转"
        server: my-docker
        container: prometheus

    - Watchtower:
        icon: watchtower.svg
        href: "docker logs watchtower"
        description: "注  - 注  砖  拽专 专住转 砖转 转专"
        server: my-docker
        container: watchtower

- " AI  转拽":
    - Open WebUI:
        icon: openai.svg
        href: https://ai.mbs-home.ddns.net
        description: "砖拽 AI 转拽 - 砖 注  AI, 注专 转转 拽 驻转专 注转"
        server: my-docker
        container: open-webui

    - Code Server:
        icon: vscode.svg
        href: https://code.mbs-home.ddns.net
        description: "VS Code 驻驻 - 住转 驻转  转 专 -VPN"
        server: my-docker
        container: code-server

    - WebSSH:
        icon: terminal.svg
        href: https://ssh.mbs-home.ddns.net
        description: "SSH 驻驻 - 砖 转 砖专转 专 驻驻"
        server: my-docker
        container: webssh

    - File Browser:
        icon: files.svg
        href: https://files.mbs-home.ddns.net
        description: " 拽爪 驻驻 - 砖 专 转 拽爪"
        server: my-docker
        container: filebrowser

    - WireGuard:
        icon: wireguard.svg
        href: https://vpn.mbs-home.ddns.net
        description: "VPN  - 砖 专拽 转  砖专转 专砖转 转转"
        server: my-docker
        container: wireguard

- "   住住转":
    - Vaultwarden:
        icon: bitwarden.svg
        href: https://vault.mbs-home.ddns.net
        description: " 住住转  - 住  砖 住住转, 专住 砖专 注 专砖"
        server: my-docker
        container: vaultwarden
    - Authelia SSO:
        icon: shield.svg
        href: https://auth.mbs-home.ddns.net
        description: "注专转 SSO 专转 - 转专转 转  砖专转 注 专砖转 转拽转"
        server: my-docker
        container: authelia

    - Firefly III:
        icon: finance.svg
        href: https://money.mbs-home.ddns.net
        description: " 爪转 砖转祝 - 转拽爪, 拽专转, 转 拽 "
        server: my-docker
        container: firefly-iii

- " 转拽砖专转 ":
    - Mail Server:
        icon: mail.svg
        href: https://mail.mbs-home.ddns.net
        description: "砖专转  驻专 - 砖转 拽转 , 转专转 专 注专转"
        server: my-docker
        container: mailserver

- "  爪":
    - Backup System:
        icon: backup.svg
        href: "docker logs backup"
        description: "注专转  转 -   砖  转 专转"
        server: my-docker
        container: backup

- " 砖转转 转":
    - Home Assistant:
        icon: home-assistant.svg
        href: https://home.mbs-home.ddns.net
        description: "专 砖转转  - 爪 砖 转,  砖专  专爪 "
        server: my-docker
        container: homeassistant